### PR TITLE
OBlElement>>styles removed

### PR DESCRIPTION
**Pull request by Enzo-Demeulenaere**
I don't know why OBlElement>>styles was returning nil but some of my elements couldn't be displayed making my spaces all black and bugged

Is there a reason this was returning nil ?

### CODE REVIEW

**Comment by Enzo-Demeulenaere** [comment]
removing it makes the lookup send ```BlElement>>styles``` and so return valid styles

**Comment by tinchodias** [comment]
I think @plantec pushed a recent change at this respect, or am i wrong?

**Comment by plantec** [comment]
styles returns nil on purpose because I think it has nothing to do at the top level of element hierarchy.
the idea was to check if it can be removed from BlElement without bad consequence.

Can you point me to your example that don't work without styles ?

Thanks

**Comment by Enzo-Demeulenaere** [comment]
Yes you can load my project with this: 

```
Metacello new
    baseline:'MineSweeper';
    repository: 'github://Enzo-Demeulenaere/MineSweeper:master/repository';
    load: 'core'
```

and execute with ```MMinesweeper openWithMenuBar```

**Comment by plantec** [comment]
Use OBlSpace instead of BlSpace and it should be ok

**Pull request closed without merging**
